# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.4.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: jupyter@googlegroups.com
author_name: Project Jupyter
has_binder: false
has_settings: true
kind: frontend
labextension_name: floating-chat
project_short_description: A JupyterLab extension to add a floating chat.
python_name: floating_chat
repository: https://github.com/brichet/floating-chat
test: true

